// -*- C++ -*-
//
// generated by wxGlade 1.1.0b1 on Fri Aug  9 23:34:07 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "BaseExchangeStatusDialog.hpp"

// begin wxGlade: ::extracode
// end wxGlade


BaseExchangeStatusDialog::BaseExchangeStatusDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: BaseExchangeStatusDialog::BaseExchangeStatusDialog
    SetTitle(_("Exchange Status"));
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxGridSizer* grid_sizer_1 = new wxGridSizer(2, 2, 0, 0);
    sizer_1->Add(grid_sizer_1, 0, wxEXPAND, 0);
    wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, _("Exchange"));
    grid_sizer_1->Add(label_1, 0, wxALIGN_RIGHT|wxALL, 5);
    txtExchangeStatus = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE|wxTE_READONLY);
    grid_sizer_1->Add(txtExchangeStatus, 0, wxEXPAND, 0);
    wxStaticText* label_2 = new wxStaticText(this, wxID_ANY, _("Trading"));
    grid_sizer_1->Add(label_2, 0, wxALIGN_RIGHT|wxALL, 5);
    txtTradingStatus = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE|wxTE_READONLY);
    grid_sizer_1->Add(txtTradingStatus, 0, wxEXPAND, 0);
    
    // WARNING: Code for instance "sizer_2" of "wxStdDialogButtonSizer" not generated: no suitable writer found
    
    button_OK = new wxButton(this, wxID_OK, wxEmptyString);
    button_OK->SetDefault();
    
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    SetAffirmativeId(button_OK->GetId());
    
    Layout();
    // end wxGlade
}

