// -*- C++ -*-
//
// generated by wxGlade 1.1.0b1 on Fri Aug  9 23:34:07 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "BaseExchangeScheduleDialog.hpp"

// begin wxGlade: ::extracode
// end wxGlade


BaseExchangeScheduleDialog::BaseExchangeScheduleDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: BaseExchangeScheduleDialog::BaseExchangeScheduleDialog
    SetTitle(_("Exchange Schedule"));
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxStaticText* label_11 = new wxStaticText(this, wxID_ANY, _("Standard Hours"));
    sizer_1->Add(label_11, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);
    wxGridSizer* grid_sizer_1 = new wxGridSizer(7, 2, 0, 0);
    sizer_1->Add(grid_sizer_1, 1, wxEXPAND, 0);
    wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, _("Sunday"));
    grid_sizer_1->Add(label_1, 0, wxALIGN_RIGHT|wxALL, 5);
    txtSundaySchedule = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE|wxTE_READONLY);
    grid_sizer_1->Add(txtSundaySchedule, 0, wxEXPAND, 0);
    wxStaticText* label_2 = new wxStaticText(this, wxID_ANY, _("Monday"));
    grid_sizer_1->Add(label_2, 0, wxALIGN_RIGHT|wxALL, 5);
    txtMondaySchedule = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE|wxTE_READONLY);
    grid_sizer_1->Add(txtMondaySchedule, 0, wxEXPAND, 0);
    wxStaticText* label_3 = new wxStaticText(this, wxID_ANY, _("Tuesday"));
    grid_sizer_1->Add(label_3, 0, wxALIGN_RIGHT|wxALL, 5);
    txtTuesdaySchedule = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE|wxTE_READONLY);
    grid_sizer_1->Add(txtTuesdaySchedule, 0, wxEXPAND, 0);
    wxStaticText* label_4 = new wxStaticText(this, wxID_ANY, _("Wednesday"));
    grid_sizer_1->Add(label_4, 0, wxALIGN_RIGHT|wxALL, 5);
    txtWednesdaySchedule = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE|wxTE_READONLY);
    grid_sizer_1->Add(txtWednesdaySchedule, 0, wxEXPAND, 0);
    wxStaticText* label_5 = new wxStaticText(this, wxID_ANY, _("Thursday"));
    grid_sizer_1->Add(label_5, 0, wxALIGN_RIGHT|wxALL, 5);
    txtThursdaySchedule = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE|wxTE_READONLY);
    grid_sizer_1->Add(txtThursdaySchedule, 0, wxEXPAND, 0);
    wxStaticText* label_6 = new wxStaticText(this, wxID_ANY, _("Friday"));
    grid_sizer_1->Add(label_6, 0, wxALIGN_RIGHT|wxALL, 5);
    txtFridaySchedule = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE|wxTE_READONLY);
    grid_sizer_1->Add(txtFridaySchedule, 0, wxEXPAND, 0);
    wxStaticText* label_7 = new wxStaticText(this, wxID_ANY, _("Saturday"));
    grid_sizer_1->Add(label_7, 0, wxALIGN_RIGHT|wxALL, 5);
    txtSaturdaySchedule = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE|wxTE_READONLY);
    grid_sizer_1->Add(txtSaturdaySchedule, 0, wxEXPAND, 0);
    panel_1 = new wxPanel(this, wxID_ANY);
    sizer_1->Add(panel_1, 1, wxEXPAND, 0);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    wxStaticText* label_8 = new wxStaticText(panel_1, wxID_ANY, _("Scheduled Maintenance Closures"));
    sizer_3->Add(label_8, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);
    wxGridSizer* grid_sizer_2 = new wxGridSizer(1, 2, 0, 0);
    sizer_3->Add(grid_sizer_2, 1, wxEXPAND, 0);
    wxStaticText* label_9 = new wxStaticText(panel_1, wxID_ANY, _("Start"));
    grid_sizer_2->Add(label_9, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);
    wxStaticText* label_10 = new wxStaticText(panel_1, wxID_ANY, _("End"));
    grid_sizer_2->Add(label_10, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);
    
    // WARNING: Code for instance "sizer_2" of "wxStdDialogButtonSizer" not generated: no suitable writer found
    
    button_OK = new wxButton(this, wxID_OK, wxEmptyString);
    button_OK->SetDefault();
    
    panel_1->SetSizer(sizer_3);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    SetAffirmativeId(button_OK->GetId());
    
    Layout();
    // end wxGlade
}

