// -*- C++ -*-
//
// generated by wxGlade 1.1.0b1 on Fri Aug  9 23:34:07 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "BaseLoginDialog.hpp"

// begin wxGlade: ::extracode
// end wxGlade


BaseLoginDialog::BaseLoginDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: BaseLoginDialog::BaseLoginDialog
    SetTitle(_("Login"));
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(2, 2, 0, 0);
    sizer_1->Add(grid_sizer_1, 0, wxALL|wxEXPAND, 0);
    wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, _("Email"));
    grid_sizer_1->Add(label_1, 0, wxALIGN_RIGHT|wxALL, 5);
    txtEmail = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    txtEmail->SetFocus();
    grid_sizer_1->Add(txtEmail, 0, wxALL|wxEXPAND, 5);
    wxStaticText* label_2 = new wxStaticText(this, wxID_ANY, _("Password"));
    grid_sizer_1->Add(label_2, 0, wxALIGN_RIGHT|wxALL, 5);
    txtPassword = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PASSWORD);
    grid_sizer_1->Add(txtPassword, 0, wxALL|wxEXPAND, 5);
    chkRememberMe = new wxCheckBox(this, wxID_ANY, _("Remember me"));
    sizer_1->Add(chkRememberMe, 0, wxALL, 5);
    
    // WARNING: Code for instance "sizer_2" of "wxStdDialogButtonSizer" not generated: no suitable writer found
    
    button_OK = new wxButton(this, wxID_OK, wxEmptyString);
    button_OK->SetDefault();
    button_CANCEL = new wxButton(this, wxID_CANCEL, wxEmptyString);
    
    grid_sizer_1->AddGrowableCol(1);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    SetAffirmativeId(button_OK->GetId());
    SetEscapeId(button_CANCEL->GetId());
    
    Layout();
    // end wxGlade
}

