// -*- C++ -*-
//
// generated by wxGlade 1.1.0b1 on Fri Aug  9 15:39:27 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "ExchanceAnnouncementsDialog.hpp"

// begin wxGlade: ::extracode
// end wxGlade


ExchanceAnnouncementsDialog::ExchanceAnnouncementsDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: ExchanceAnnouncementsDialog::ExchanceAnnouncementsDialog
    SetTitle(_("Exchange Announcements"));
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    panel_1 = new wxPanel(this, wxID_ANY);
    sizer_1->Add(panel_1, 1, wxEXPAND, 0);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(1, 4, 0, 0);
    wxStaticText* label_1 = new wxStaticText(panel_1, wxID_ANY, _("Time"));
    grid_sizer_1->Add(label_1, 0, wxALL, 5);
    wxStaticText* label_2 = new wxStaticText(panel_1, wxID_ANY, _("Status"));
    grid_sizer_1->Add(label_2, 0, wxALL, 5);
    wxStaticText* label_3 = new wxStaticText(panel_1, wxID_ANY, _("Type"));
    grid_sizer_1->Add(label_3, 0, wxALL, 5);
    wxStaticText* label_4 = new wxStaticText(panel_1, wxID_ANY, _("Message"));
    grid_sizer_1->Add(label_4, 0, wxALL, 5);
    
    // WARNING: Code for instance "sizer_2" of "wxStdDialogButtonSizer" not generated: no suitable writer found
    
    button_OK = new wxButton(this, wxID_OK, wxEmptyString);
    button_OK->SetDefault();
    
    grid_sizer_1->AddGrowableCol(3);
    panel_1->SetSizer(grid_sizer_1);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    SetAffirmativeId(button_OK->GetId());
    
    Layout();
    // end wxGlade
}

