// -*- C++ -*-
//
// generated by wxGlade 1.1.0b1 on Fri Aug  9 15:39:27 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "LogoutDialog.hpp"

// begin wxGlade: ::extracode
// end wxGlade


LogoutDialog::LogoutDialog(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: LogoutDialog::LogoutDialog
    SetTitle(_("Confirm"));
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxStaticText* label_1 = new wxStaticText(this, wxID_ANY, _("Logout?"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
    sizer_1->Add(label_1, 0, wxALL|wxEXPAND, 5);
    
    // WARNING: Code for instance "sizer_2" of "wxStdDialogButtonSizer" not generated: no suitable writer found
    
    button_OK = new wxButton(this, wxID_OK, wxEmptyString);
    button_OK->SetDefault();
    button_CANCEL = new wxButton(this, wxID_CANCEL, wxEmptyString);
    
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    SetAffirmativeId(button_OK->GetId());
    SetEscapeId(button_CANCEL->GetId());
    
    Layout();
    // end wxGlade
}

