// -*- C++ -*-
//
// generated by wxGlade 1.1.0b1 on Fri Aug  9 15:39:27 2024
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef MAINFRAME_HPP
#define MAINFRAME_HPP

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "App"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include "ui/StaticCurrency.hpp"
// end wxGlade


class MainFrame: public wxFrame {
public:
    // begin wxGlade: MainFrame::ids
    // end wxGlade

    MainFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:

protected:
    // begin wxGlade: MainFrame::attributes
    wxMenuItem* mnuLogin;
    wxMenuItem* mnuLogout;
    wxMenuItem* mnuShowClosedPositions;
    wxMenuBar* frame_menubar;
    wxStatusBar* frame_statusbar;
    wxPanel* panel_1;
    StaticCurrency* text_ctrl_1;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnMenuItemSelected(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void ---(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // MAINFRAME_HPP
