name: Debian Bookworm Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # allows manual execution of the workflow

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t kdeck-build .

      - name: Run build in Docker container
        run: docker run -v "kdeck-build-volume:/src/build" kdeck-build

      - name: Store build output location
        id: vars
        run: echo "volume_path=$(docker volume inspect --format '{{ .Mountpoint }}' kdeck-build-volume)" >> $GITHUB_OUTPUT

      # - name: Create tarball
      #   run: tar -czvf release.tar.gz build/bin/Linux64/Release/kdeck

      - name: List build output
        run: ls -R "{{ steps.vars.outputs.volume_path }}"

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: release.tar.gz
      #     path: release.tar.gz