name: Debian Bookworm Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # allows manual execution of the workflow

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Build and package
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: Dockerfile
      #     push: false
      #     tags: kdash-build:latest

      - name: Build Docker image
        run: docker build -t kdeck-build .

      - name: Run build in Docker container
        #run: docker run -v "$(pwd):/src" kdeck-build
        run: docker run -v "build:/src/build" kdeck-build

      # - name: Create tarball
      #   run: |
      #     mkdir release
      #     cp path/to/executable release/
      #     cp path/to/LICENSE release/
      #     tar -czvf release.tar.gz release/

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: release-artifact
      #     path: release.tar.gz