name: Debian Bookworm Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # allows manual execution of the workflow

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t kdeck-build .

      # NOTE: We use a bind-mount instead of a volume because the runner user
      #       does not have permission to access a created volume.

      - name: Run build in Docker container
        run: docker run -v "$GITHUB_WORKSPACE/build:/src/build" kdeck-build

      - name: Create tarball
        run: tar -czvf release.tar.gz "$GITHUB_WORKSPACE/build/bin/Linux64/Release/kdeck"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            release.tar.gz
            LICENSE.md
